<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="piaoyao-4.local" name="接口测试套件demo" tests="2" failures="1" timestamp="17 Oct 2019 07:15:52 GMT" time="0.022" errors="0">
  <testcase name="testcase1" time="0.002" classname="com.course.demo.TestDemo"/>
  <testcase name="testcase2" time="0.0" classname="com.course.demo.TestDemo">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at com.course.demo.TestDemo.testcase2(TestDemo.java:20)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testcase2 -->
</testsuite> <!-- 接口测试套件demo -->
