<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="bogon" ignored="0" name="飘摇的接口测试套件" tests="2" failures="1" timestamp="06 Oct 2019 03:43:45 GMT" time="0.025" errors="0">
  <testcase name="testcase1" time="0.001" classname="com.course.demo.TestDemo"/>
  <testcase name="testcase2" time="0.002" classname="com.course.demo.TestDemo">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at com.course.demo.TestDemo.testcase2(TestDemo.java:17)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- testcase2 -->
</testsuite> <!-- 飘摇的接口测试套件 -->
